### ISSUE TITLE
6 - Criar documentação do jogo.

### ISSUE THREAD

**Issue by ricardofsilva7** [Game-JAVA/Low-Code#5]
# Topicos

## Descrição

> Descrição do jogo

## Instruções

> Tela de bem vindo
> descrição da gameplay (caracteristicas)

## Controles

> como funciona/quais botões utilizar

## Requisitos

> Requisitos para rodar o jogo

## Instalação

> Instrução para instalação do jogo

**Comment by scryng** [comment]
Divisão da tarefa:

Cabeçalho -  @scryng 
Descrição - @ceduardooliveira 
Instruções - @vinicinnnn 
Controles - @ricardofsilva7 
Requisitos - @ricardofsilva7 e @scryng 
Instalação - @scryng
