### ISSUE TITLE
7 - Criação de tela inicial e de controles

### ISSUE THREAD

**Issue by ricardofsilva7** [Game-JAVA/Low-Code#7]
# Tela de inicio
> Tela com as  opções de 'Start Game' , 'Controls' e 'Exit'

# Tela de controles
> Tela com orientações de controles do jogo

**Comment by vinicinnnn** [comment]
# Tela de inicio




![Image](https://github.com/Game-JAVA/Low-Code/assets/149544575/85291c8c-22b8-40b0-b1ee-b801ad1a7661)


# Tela de controles



![Image](https://github.com/Game-JAVA/Low-Code/assets/149544575/e9daaf51-f54b-459c-88e0-33b962e75e58)
